In [53]:
import torch
import numpy as np

In [54]:
x = torch.rand(3,3)
y = torch.randn(5)

In [55]:
x

tensor([[0.3482, 0.9347, 0.2723],
        [0.5228, 0.5320, 0.6853],
        [0.4628, 0.1140, 0.5778]])

In [56]:
y

tensor([-0.0869,  1.1839,  1.5990, -0.6043, -0.7991])

In [57]:
# numpy to tensor
a = np.array([1,2,3,4])
b = torch.Tensor(a)

b

tensor([1., 2., 3., 4.])

In [58]:
# tensor to numpy
c = torch.rand(4)
d = c.numpy()

d

array([0.02686697, 0.30774194, 0.2322647 , 0.3189718 ], dtype=float32)

In [59]:
# tensor의 형태 변환
t = torch.rand(3,3)
t = t.view(1,1,3,3)

t

tensor([[[[0.9210, 0.4005, 0.8945],
          [0.0867, 0.8756, 0.8907],
          [0.6608, 0.2472, 0.0302]]]])

In [60]:
# tensor 계산을 GPU로
if torch.cuda.is_available():
    e = e.cuda()
    f = f.cuda()
    sum = e+f
    print(sum)

In [62]:
t.device

device(type='cpu')

In [63]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [64]:
# tensor 합치기
# torch.cat((TensorA, TensorB), dim)

t1 = torch.cat([tensor, tensor, tensor], 0)
print('t1: ', t1)
t2 = torch.cat([tensor, tensor, tensor], 1)
print('t2: ', t2)

t1:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
t2:  tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [65]:
# 두 텐서 간의 행렬 곱(matrix multiplication)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [66]:
# tensor의 모든 값을 하나로 집계
agg = tensor.sum()
print(agg)

# 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [67]:
# 바꿔치기(in-place) 연산 
# 연산 결과를 피연산자(operand)에 저장하는 연산
tensor.add_(6)
print(tensor)

tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])
