In [20]:
import torch
from torch.autograd import Variable

In [21]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [22]:
x = Variable(a, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [24]:
z = 2*y**2
print(z)

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)


In [25]:
res = z.mean()
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [26]:
# res = (z_1 + .. + z_4)/4
# z_i = 2*(x_i+1)**2
# 따라서 d(res)/dx_i) = x_i + 1

res.backward()

In [27]:
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
None


In [28]:
print(y.data)
print(y.grad)
print(y.grad_fn)

tensor([[2., 2.],
        [2., 2.]])
None


/var/folders/lz/1j0xrzv96vb0c0thtnh_wmjw0000gn/T/ipykernel_90370/579703269.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(y.grad)


In [29]:
print(z.data)
print(z.grad)
print(z.grad_fn)

tensor([[8., 8.],
        [8., 8.]])
None


/var/folders/lz/1j0xrzv96vb0c0thtnh_wmjw0000gn/T/ipykernel_90370/3572386746.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(z.grad)


In [30]:
print(res.data)
print(res.grad)
print(res.grad_fn)

tensor(8.)
None


/var/folders/lz/1j0xrzv96vb0c0thtnh_wmjw0000gn/T/ipykernel_90370/1444058415.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(res.grad)
